### PR TITLE
Feat: Support fallbacks

### LINKED ISSUE #4: Feature Request: Custom Handlers
## Feature

I want to be able to customise how `valueToEstree` converts an object to estree.

The solution I'm thinking of, would be providing an `handlers` option for handling different types.

For example, disable it only for objects containing a special property.

```ts
valueToEstree(value, {
  handlers: {
    object: (v) => isHast(v)? hastToEstree(v) : undefined
  |
})
```

When `undefined` is returned, use the default behavour.

## Additional context

I was trying to inject an object as the prop of a MDX element. Now I have an object like:

```jsx
{
  name: "Hello",
  description: "Markdown Content"
}
```

to convert it into estree, I have to first compile the markdown content `description` to HAST tree, and use `hast-util-to-estree` to make it an estree.

```jsx
{
  name: "Hello",
  description: { ... } // ES Tree
}
```

Now I will use this utility to convert the whole object into estree. But it apparently will treat the `description` property as an ordinary object, hence it can't give my desired result.

I fixed it by manipulating the estree afterwards, would like to see if this can be done with this library.

### PR DESCRIPTION
**Pull request by fuma-nama**
## Why?

Allow people to customise how it handles custom class instances.

## Usage

```ts
valueToEstree(value, {
  fallback: v => {
    // return an expression
  }
}); 
```

## Tests

Added a test for custom fallbacks, all tests passed.

This can close #4 since it is possible to skip processing a value by wrapping it in a custom class and handle it with a fallback.

### CODE REVIEW

**Comment by wooorm** [comment]
This is a bit different from the earlier request. Why?

It also reminds me a lot of the "reviver" for JSON. Would it be good to use a same API?

**Comment by fuma-nama** [comment]
That's an interesting idea, to implement the handler API I initially suggested, we need a breaking change to the current implementation. This is equivalent to a rewrite while a fallback option is enough to solve my problem.

I'm willing to implement that if you're interested

**Comment by wooorm** [comment]
Huh? What is “breaking” about the other idea?
And, the “fallback” idea, so this PR, seems similar to the “reviver” to me, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver but would be a little different. What do you think about that?

But these where more questions that I had. It all depends more on what @remcohaszing is thinking, as it’s their project!

**Comment by fuma-nama** [comment]
I think `replacer` from `JSON.stringify` is more similar than `reviver`, anyway it's just about naming and won't make much difference.

**Pull request closed without merging**
